
CREATE TABLE `stock` (
  `T1_STOCK_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `T1_STOCK_CODE` VARCHAR(10) NOT NULL,
  `T1_STOCK_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`T1_STOCK_ID`) USING BTREE,
  UNIQUE KEY `UNI_STOCK_NAME` (`T1_STOCK_NAME`),
  UNIQUE KEY `UNI_STOCK_ID` (`T1_STOCK_CODE`) USING BTREE
)

CREATE TABLE `category` (
  `T2_CATEGORY_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `T2_NAME` VARCHAR(10) NOT NULL,
  `T2_DESC` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`T2_CATEGORY_ID`) USING BTREE
)

CREATE TABLE  `stock_category` (
  `T3_STOCK_ID` INT(10) UNSIGNED NOT NULL,
  `T3_CATEGORY_ID` INT(10) UNSIGNED NOT NULL,
  `T3_CREATED_DATE` DATE NOT NULL,
  `T3_CREATED_BY` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`T3_STOCK_ID`,`T3_CATEGORY_ID`),
  CONSTRAINT `FK_CATEGORY_ID` FOREIGN KEY (`T3_CATEGORY_ID`)
             REFERENCES `category` (`T2_CATEGORY_ID`),
  CONSTRAINT `FK_STOCK_ID` FOREIGN KEY (`T3_STOCK_ID`)
             REFERENCES `stock` (`T1_STOCK_ID`)
)